# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': 'Intercompany Transaction Extension',
    'sequence': 1,
    'author': 'Mohamed Yaseen Dahab',
    'category': 'Sales/Sales',
    'summary': 'Generate new PO from the intercompany generated SO',
    'description': """
    The default Behavior of Intercompany transaction is to Generate SO in second Company from the created PO in the First Company
    This Module extension generate further PO from the second company SO which is by its own generated by Intercompany

    """,
    'version': '1.0',
    'depends': ['base', 'stock', 'account', 'sale', 'purchase','account_inter_company_rules','sale_purchase_inter_company_rules'],
    'data': [
        'security/ir.model.access.csv',
        'views/res_config_settings_views.xml',
        'views/inherit_stock_picking_view.xml',
        'views/purchase_order_views.xml',
        'views/purchase_order_template_views.xml',
        'views/putchase_tag_views.xml',
        'views/inherit_sale_order_view.xml',
        'views/inherit_account_view.xml',
        'report/inherit_po_report.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
